{"name": "test_void_add", "status": "failed", "statusDetails": {"message": "AssertionError: assert [(314, '', ''..., 1, 0, None)] == []\n  Left contains one more item: (314, '', '', '', 1, 0, None)\n  Full diff:\n  - [(314, '', '', '', 1, 0, None)]\n  + []", "trace": "self = <test_api.Test_Api object at 0x00000231916AFC40>\nsql_client = <sql_client.client.MysqlOrmConnection object at 0x000002319178DB20>\n\n    @allure.story('other')\n    @pytest.mark.other\n    def test_void_add(self, sql_client):\n        \"\"\"Проверка, добавления через API абсолютно пустого пользователя\"\"\"\n        if sql_client.select('username', '') != []:\n            try:\n                sql_client.delete('username', '')\n            except Exception:\n                pass\n        status_code = self.client.add({\n            'user': '',\n            'password': '',\n            'email': ''\n        }).status_code\n>       assert sql_client.select('username', '') == []\nE       AssertionError: assert [(314, '', ''..., 1, 0, None)] == []\nE         Left contains one more item: (314, '', '', '', 1, 0, None)\nE         Full diff:\nE         - [(314, '', '', '', 1, 0, None)]\nE         + []\n\ntests\\test_api.py:68: AssertionError"}, "description": "Проверка, добавления через API абсолютно пустого пользователя", "start": 1590592369818, "stop": 1590592369894, "uuid": "a46a84ab-6f3c-47b2-a321-01e86849faf5", "historyId": "610a62e06087617aa3870617c0e248ae", "testCaseId": "ef8b4688f2fd18b822f82d7a123b3478", "fullName": "tests.test_api.Test_Api#test_void_add", "labels": [{"name": "story", "value": "other"}, {"name": "tag", "value": "other"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "Test_Api"}, {"name": "host", "value": "DESKTOP-4CMVFT5"}, {"name": "thread", "value": "15136-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}