{"name": "test_hell_user_auth", "status": "passed", "description": "Проверка, что при входе с невозможно длинным паролем приложение\n        реагирует корректно", "start": 1590592384526, "stop": 1590592390546, "uuid": "8ffdf6ea-d932-45c5-9362-baae3a9b5766", "historyId": "01d629f4513d96b672bf6065d657981a", "testCaseId": "bb386e997c15435218050a60451d19b3", "fullName": "tests.test_ui.Test_UI_Auth#test_hell_user_auth", "labels": [{"name": "story", "value": "other"}, {"name": "tag", "value": "other"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_ui"}, {"name": "subSuite", "value": "Test_UI_Auth"}, {"name": "host", "value": "DESKTOP-4CMVFT5"}, {"name": "thread", "value": "15136-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_ui"}]}