{"name": "test_hell_add_email", "status": "failed", "statusDetails": {"message": "AssertionError: assert 210 == 400\n  -210\n  +400", "trace": "self = <test_api.Test_Api object at 0x000002AE40F8DA60>\ndata_to_create = {'email': 'BBBBBp@fff.ku', 'password': 'aaaaa#zzzzz', 'user': 'Test_name1702'}\nsql_client = <sql_client.client.MysqlOrmConnection object at 0x000002AE40FC1550>\n\n    @allure.story('other')\n    @pytest.mark.other\n    def test_hell_add_email(self, data_to_create, sql_client):\n        \"\"\"Проверка реакции приложения на создание пользователя\n        с невозможно длинным email\"\"\"\n        request = self.client.add({\n            'user': data_to_create['user'],\n            'password': '',\n            'email': 'a' * 256})\n        assert sql_client.select('username', data_to_create['user']) == []\n>       assert request.status_code == 400\nE       assert 210 == 400\nE         -210\nE         +400\n\ntests\\test_api.py:107: AssertionError"}, "description": "Проверка реакции приложения на создание пользователя\n        с невозможно длинным email", "start": 1590592369807, "stop": 1590592369876, "uuid": "854311ce-eac2-4263-892c-661d95217f62", "historyId": "a31d9c67ab0fbb6d9c3ba7c6dbcd2c9c", "testCaseId": "48e6cb3ffe38638d2c48e3fd759d570f", "fullName": "tests.test_api.Test_Api#test_hell_add_email", "labels": [{"name": "story", "value": "other"}, {"name": "tag", "value": "other"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "Test_Api"}, {"name": "host", "value": "DESKTOP-4CMVFT5"}, {"name": "thread", "value": "9312-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}