{"name": "test_add", "status": "failed", "statusDetails": {"message": "AssertionError: assert 210 == 201\n  -210\n  +201", "trace": "self = <test_api.Test_Api object at 0x00000242D682F850>\ndata_to_create = {'email': 'OOOOOOOOOOJ@ffff.ku', 'password': 'a#zzzzzz', 'user': 'Test_name5953'}\nsql_client = <sql_client.client.MysqlOrmConnection object at 0x00000242D690DB20>\n\n    @allure.story('main')\n    @pytest.mark.main\n    def test_add(self, data_to_create, sql_client):\n        \"\"\"Проверка создания пользователя через API\"\"\"\n        request = self.client.add(data_to_create)\n        print(sql_client.select('username', data_to_create['user']))\n        password = sql_client.select('username', data_to_create['user'])[0][2]\n        assert password == data_to_create['password']\n        status_code = request.status_code\n>       assert status_code == 201\nE       assert 210 == 201\nE         -210\nE         +201\n\ntests\\test_api.py:27: AssertionError"}, "description": "Проверка создания пользователя через API", "start": 1590592369674, "stop": 1590592369799, "uuid": "f89011ce-d106-41fe-9dc1-49ba1a2819f2", "historyId": "ee43251cc4f97bfb2e891f995baec817", "testCaseId": "1ce0ba79a8244f8b9f43880a2d4b9dfa", "fullName": "tests.test_api.Test_Api#test_add", "labels": [{"name": "story", "value": "main"}, {"name": "tag", "value": "main"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "Test_Api"}, {"name": "host", "value": "DESKTOP-4CMVFT5"}, {"name": "thread", "value": "15276-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}