{"name": "test_hell_add", "status": "failed", "statusDetails": {"message": "AssertionError: assert 210 == 400\n  -210\n  +400", "trace": "self = <test_api.Test_Api object at 0x000001AB17010C10>\ndata_to_create = {'email': 'ttttr@ff.ku', 'password': 'aaaaa#zzzzzz', 'user': 'Test_name5817'}\nsql_client = <sql_client.client.MysqlOrmConnection object at 0x000001AB170EDB50>\n\n    @allure.story('other')\n    @pytest.mark.other\n    def test_hell_add(self, data_to_create, sql_client):\n        \"\"\"Проверка реакции на создание пользователя с невозможно\n        длинным именем\"\"\"\n        request = self.client.add({\n            'user': 'a' * 256,\n            'password': data_to_create['password'],\n            'email': data_to_create['email']\n        })\n        assert sql_client.select('email', data_to_create['email']) == []\n>       assert request.status_code == 400\nE       assert 210 == 400\nE         -210\nE         +400\n\ntests\\test_api.py:82: AssertionError"}, "description": "Проверка реакции на создание пользователя с невозможно\n        длинным именем", "start": 1590592369644, "stop": 1590592369751, "uuid": "7f1eaeec-abcf-4ab3-9e2b-6dd77999009a", "historyId": "75f31abd5e6ec7a8f3c67f26ebb7ff4b", "testCaseId": "947e46ed607b6997cb0716e27f5efc85", "fullName": "tests.test_api.Test_Api#test_hell_add", "labels": [{"name": "story", "value": "other"}, {"name": "tag", "value": "other"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "Test_Api"}, {"name": "host", "value": "DESKTOP-4CMVFT5"}, {"name": "thread", "value": "26464-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}